### ISSUE TITLE
Issue #11

### ISSUE THREAD

**Issue by DennyTim** [RohitSavalagi/AssignmentPage#11]
https://github.com/RohitSavalagi/AssignmentPage/blob/0a97f35fb33911b55d465fafdeabca13e62922da/style.css#L102

Contextually right way with width, but better to bring a special container for each section of the page.
If you wanna use width restrictions for the page, you need to use the following structure:

```html
<header class="...">
   <div class="container">...</div>
</header>
<main class="...">
   <div class="container">...</div>
</main >
<footer class="...">
   <div class="container">...</div>
</footer>
```
```css
.container {
    width: 960px;
    margin: 0 auto;
    text-align: center; /* can be used optionally if you wanna align the whole section */
}
```
